### ISSUE TITLE
Not loading settings/prefs.ttl

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-logic#8]
See https://gitter.im/solid/solidcommunity.net?at=5fb41decbf955735eb8672aa

**Comment by timbl** [comment]
As the GET comes back with a 401 unauthenticated and nothing more is done about it does this suggest this is a problem in solid-auth-client?

**Comment by michielbdejong** [comment]
Ah, but I tried to log in to https://michielbdejong.solidcommunity.net/public/ using my https://michielbdejong.solidweb.org/profile/card#me identity, and could not reproduce this bug.

Also from https://gitter.im/solid/solidcommunity.net?at=5fb6583dbf955735eb8be3cf it seems that timbl.com was using an outdated custom mashlib, so that was probably causing that.
See also https://gitter.im/solid/solidos?at=5fb65d132a354407153544bd

Closing this now, @timbl please reopen if the issue reappears.

Thanks!
